name: Package Application with Pyinstaller
env:
  project-name: ez.gg
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set archive name
      run: |
        ARCHIVE_NAME=${{ env.project-name }}-`git describe --always`-${{ matrix.platform-name }}
        echo "Archive name set to: $ARCHIVE_NAME"
        echo "archive-name=$ARCHIVE_NAME" >> $GITHUB_ENV
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: ez.gg-alpha-v00.0${{ github.run_number }}
        path: src/dist/windows

    - name: Upload release
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.archive-name }}.*
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
