name: Package Application with Pyinstaller

on:
  push:
    branches: [ master, build-test ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: ez.gg-beta-v0.1.1-build-${{ github.run_number }}
        path: src/dist/windows
